spring.application.name=Diploma
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migration/migration.xml
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/diplomadb
spring.datasource.username=diploma_user
spring.datasource.password=diploma_password
security.jwt.secret=change-me-to-a-long-secret-key-at-least-32-characters
security.jwt.expiration-ms=3600000
